CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE reports(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT,
    result TEXT
);
